name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - master*
      - release*

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: "Generate next build number"
        id: version
        uses: "symless/next-version-action"
        with:
          current-version: $(cat VERSION)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next-version }}
          release_name: ${{ steps.version.outputs.next-version }}
          commitish: master
          draft: false
          prerelease: true
