name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - master*
      - release*

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Read version file
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get next version
        id: version
        uses: symless/next-version-action@master
        with:
          current-version: ${{ env.VERSION }}

      - name: Print next version
        run: echo ${{ steps.version.outputs.next-version }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next-version }}
          release_name: ${{ steps.version.outputs.next-version }}
          commitish: master
          draft: false
          prerelease: true
